import React from 'react'
import { Modal } from '../../src'

const LongModal = (props) => (
  <Modal
    title="Long, Scrolling Modal"
    {...props}
  >
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras aliquet metus malesuada est rhoncus, et iaculis sapien ullamcorper. Aliquam dapibus varius maximus. Suspendisse potenti. Donec ut leo purus. Sed sed lectus mauris. Sed condimentum, orci et dapibus dapibus, eros dolor volutpat metus, quis convallis est ante nec libero. Praesent sed sodales tortor. Donec in enim vestibulum, sollicitudin elit interdum, gravida nisl. Fusce eleifend turpis orci, auctor dapibus erat laoreet ut. Maecenas ipsum nisi, feugiat ut finibus nec, scelerisque non velit. Nulla dignissim et orci a ullamcorper. Sed in arcu molestie, rutrum nisl vel, iaculis augue. In hac habitasse platea dictumst. In molestie elementum libero nec gravida. Morbi rhoncus ex vel consectetur vestibulum. Nulla eget velit velit.</p>

    <p>Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin iaculis ultrices est, quis pellentesque neque aliquam ac. Integer pellentesque laoreet elit, at vulputate lacus mattis in. Nam dictum consequat dui ac semper. Vestibulum leo dui, tincidunt sit amet condimentum et, luctus sit amet augue. Mauris lobortis velit tortor, nec pharetra felis luctus ut. Aenean convallis diam interdum, fringilla nisl ut, porta nibh. Cras non gravida tellus. Morbi ut ultricies mi.</p>

    <p>Pellentesque ultrices viverra elit eleifend consequat. In augue erat, tempor in finibus in, luctus vel nisl. In bibendum vehicula leo at aliquet. Aliquam luctus velit a rutrum iaculis. Vivamus non enim ut metus tincidunt aliquam. Donec commodo nisi non turpis lacinia, et vulputate risus ornare. Pellentesque non tortor quis orci auctor fringilla ac eget leo. Nulla efficitur a ligula pharetra imperdiet. Morbi auctor sem vel imperdiet lobortis. Nunc maximus nisi enim, id interdum elit auctor non. Mauris consectetur nisi non eleifend sodales. Vivamus eu dui non diam porttitor placerat.</p>

    <p>In libero tortor, mattis sed pretium at, tempus non ex. Donec placerat egestas dignissim. Nam facilisis massa orci, et blandit ex consectetur in. Nulla facilisi. Donec suscipit, eros ac facilisis iaculis, justo nibh vestibulum nisi, eu tincidunt eros nisl sit amet nisl. Vivamus mattis eu ante nec hendrerit. Nulla quis elementum urna. Vestibulum ex ipsum, consectetur id leo nec, imperdiet laoreet leo.</p>

    <p>Suspendisse vitae libero nec turpis faucibus pulvinar. Aliquam placerat euismod auctor. In ipsum libero, condimentum ac aliquam nec, faucibus rutrum nibh. Quisque orci erat, venenatis a erat id, venenatis pretium ante. Nulla justo enim, tempus et ligula facilisis, semper venenatis lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce gravida hendrerit lacus, at varius mauris vestibulum at. Etiam consequat lectus id mi mattis, mattis lobortis neque eleifend. Donec luctus libero non sodales efficitur. Maecenas volutpat orci nec lacus malesuada, non varius enim lobortis.</p>

    <p>Nunc laoreet leo non tristique cursus. Morbi mollis non tortor ac aliquam. Duis eu dolor in mi aliquam tincidunt. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam in erat id arcu facilisis ultrices sit amet ac nunc. Suspendisse non interdum ex. Vivamus fermentum purus quis mi pulvinar, sed blandit erat ornare. Sed venenatis justo non quam hendrerit, nec porttitor nibh aliquet.</p>

    <p>Sed efficitur accumsan mi, sit amet suscipit tortor convallis in. Integer posuere quam in ligula faucibus tristique ac vitae lacus. Sed fringilla euismod augue, quis ultrices arcu porttitor nec. Donec ultricies ullamcorper diam, id vulputate nunc consectetur eu. Morbi sem libero, posuere non nulla quis, suscipit tempor quam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vivamus id efficitur neque. Proin ipsum quam, laoreet et hendrerit ac, semper nec mi. Proin scelerisque at odio quis auctor. Ut tempor quam ut quam dictum auctor. Aenean laoreet mauris vel ultricies pulvinar. Integer ut felis pellentesque, rhoncus lacus sed, hendrerit nisi. Donec feugiat, sapien sit amet dictum efficitur, sem arcu euismod sapien, eget molestie ipsum mauris vel elit. Etiam ac erat mollis, commodo tortor sagittis, lobortis lacus.</p>

    <p>Sed cursus tempus leo, id dapibus nibh semper sit amet. Suspendisse non arcu egestas, suscipit arcu a, pharetra enim. Aliquam vitae sapien egestas, suscipit ligula sed, lobortis leo. Maecenas et dictum felis. Suspendisse tincidunt risus nec diam porta tincidunt. Quisque mollis, augue ut pellentesque tempus, eros ligula sagittis lorem, ut eleifend quam sapien nec nisi. Aenean rutrum lorem eget sagittis tincidunt. Praesent gravida augue eget egestas ultricies. Nullam vel odio elementum, fringilla mauris non, maximus tellus. Mauris sed arcu blandit, ultrices mauris nec, volutpat diam. Vestibulum orci erat, malesuada non elementum sed, laoreet a nisl.</p>

    <p>Morbi nec sapien suscipit, mollis leo laoreet, consectetur diam. Donec sit amet libero in nisl gravida imperdiet. Curabitur eget ex sit amet sem volutpat mollis at pharetra tortor. Etiam dui enim, consequat vel purus non, accumsan hendrerit ex. Nam a leo facilisis, bibendum odio tempus, lobortis felis. Nulla varius lorem magna, at blandit odio mollis non. Phasellus nec pharetra tellus. Donec id iaculis turpis. Donec quis eros at nunc malesuada placerat.</p>

    <p>Phasellus nibh metus, ullamcorper vel faucibus vitae, scelerisque id justo. Ut vel maximus leo, nec pellentesque ipsum. Etiam dignissim, est nec varius pretium, ligula leo aliquet enim, id sollicitudin diam mi id mi. Pellentesque eu odio vel massa iaculis tempor non ac lacus. Nam tincidunt euismod massa vel finibus. Aenean libero sapien, efficitur lobortis nibh eleifend, congue rhoncus lorem. Nam pretium urna eget sem imperdiet varius. Proin commodo ultricies malesuada. Duis euismod purus sed metus ultricies, quis tempus leo rhoncus. Duis aliquet justo ut nisl commodo, eu consequat dolor cursus. Nam ac felis a erat vulputate laoreet tincidunt id augue. Ut convallis justo id mi bibendum, vel semper nibh molestie. Sed laoreet ex nisl, at gravida neque convallis at.</p>

    <p>Aenean ut lectus nibh. Nulla hendrerit nec metus at molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent sed ante ac leo feugiat faucibus. Ut iaculis cursus eros. Maecenas malesuada lectus a ante gravida iaculis. Duis id imperdiet orci. Praesent nec nibh sit amet sapien elementum imperdiet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed aliquet commodo ante sit amet vestibulum. Duis tempus vehicula efficitur. Vivamus tincidunt, ipsum eget volutpat dignissim, tortor sapien venenatis nunc, quis efficitur nisl nisl a tellus. Pellentesque nulla ante, hendrerit in nibh in, maximus tempus magna. Morbi ullamcorper lobortis erat at molestie.</p>

    <p>Nulla ac sem nisi. Suspendisse eget ante massa. Phasellus venenatis pharetra libero, ut porttitor tortor euismod ut. Aliquam bibendum gravida leo, venenatis ornare purus tristique quis. Etiam ut tincidunt mi, vel consequat purus. Etiam accumsan nec arcu vitae tempor. Sed viverra dolor sed lectus mollis, a dignissim quam tristique. Duis vitae est augue. Etiam varius quam sit amet ligula cursus vestibulum. In tincidunt enim vel neque efficitur lobortis. Aenean suscipit aliquam enim vitae mollis. Duis vehicula imperdiet odio, eget porttitor mauris vehicula sit amet. Ut sagittis leo magna, vitae porttitor mi pretium vel. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur a euismod velit.</p>

    <p>Integer lorem eros, laoreet et sapien eget, tempor convallis est. Aenean ut felis malesuada ante feugiat vehicula. Sed sit amet imperdiet lorem. Pellentesque ac ultrices nisl. Quisque fermentum bibendum ante, fermentum posuere quam malesuada non. Maecenas ac molestie magna. Aenean nec lacinia metus. Maecenas eu dui justo. Vestibulum non eleifend leo.</p>

    <p>Phasellus a mauris commodo dui congue porttitor ut eget dolor. Vivamus odio massa, pulvinar maximus faucibus et, sagittis ac nibh. Phasellus feugiat ut neque rutrum cursus. Vivamus rhoncus risus in pretium tincidunt. Fusce euismod mi sed erat porta, id venenatis elit posuere. Phasellus metus dui, tristique vitae finibus id, vestibulum ac ante. Maecenas porta magna a sem porttitor, non volutpat sem ultricies.</p>

    <p>Praesent hendrerit dignissim est, sed pharetra metus auctor eu. Nam sed augue et elit aliquet bibendum. Sed pellentesque nibh at enim cursus, in lacinia ante condimentum. Nullam elementum justo nec nulla sodales faucibus. Donec maximus leo in posuere iaculis. Vestibulum vulputate lacinia mi. Pellentesque iaculis magna id lobortis eleifend. Vivamus auctor nulla ante, sed fringilla sapien varius viverra. Nulla eleifend mattis rutrum. Vestibulum urna eros, dapibus in imperdiet et, accumsan vel sapien. Sed venenatis urna augue, ac fringilla massa blandit ac.</p>
  </Modal>
)

export default LongModal
